numpy
  - 파이썬의 수학연산을 위해 개발된 라이브러리
  - 행렬 내적연산, 사인 코상, 벡터, 미분,적분.... 다차원 방정식
  - C언어로 개발되서 속도가 빠르다
  - 다른 라이브러리와 통합: pandas ,Scikit-learn, Tensorflow
  - 생긴건 리스트와 동일
  - 리스트와 넘파이간의 변환이 자유롭다

In [1]:
import numpy as np

In [2]:
# 1 2 3 4 5
list_1 = [1,2,3,4,5]
np.array( [1,2,3,4,5] )
np_1 = np.array( list_1 )
print(list_1)
print(np_1)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [3]:
list_1

[1, 2, 3, 4, 5]

In [4]:
np_1

array([1, 2, 3, 4, 5])

In [5]:
# 리스트의 연산
list_1 + list_1

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [6]:
np_1 + np_1

array([ 2,  4,  6,  8, 10])

In [7]:
np_1 - np_1

array([0, 0, 0, 0, 0])

In [8]:
np_1 * np_1

array([ 1,  4,  9, 16, 25])

In [9]:
np_1 / np_1

array([1., 1., 1., 1., 1.])

In [10]:
list_1 * 3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [11]:
np_1 * 3

array([ 3,  6,  9, 12, 15])

In [12]:
# np_1 -> 리스트 -> 넘파이
np.array(list(np_1))

array([1, 2, 3, 4, 5])

In [13]:
list_1 = [1,2,3,4,5,6,7,8,9,10]

In [14]:
# 필터함수.. [1 2 3 4 5 6 7 8 9 10 ] 5보다 큰 값만 추출
list(filter(lambda x : x > 5, list_1))

[6, 7, 8, 9, 10]

In [15]:
np_1 = np.array(list_1)
np_1[np_1 > 5]

array([ 6,  7,  8,  9, 10])

In [16]:
# 슬라이싱   [start : end]   -> 실제 가져올때는 start 그대로.. end만 end-1의 인덱스

In [17]:
np_1 = np.array([0,1,2,3,4,5,6,7,8,9,10])
np_1[0:2]

array([0, 1])

In [18]:
# 1 ~ 100-1 중에서 랜덤하게 10개
temp =  np.random.randint(1,100,10)
temp

array([84, 36, 91, 70, 10, 42, 26, 11, 92, 26])

In [19]:
# 첫번째 값을 출력
print(temp[0])
# 가장 마지막 값을 출력
print(temp[-1], temp[ len(temp)-1  ])
# 처음부터 3개 출력
print(temp[:3])
# 마지막에서 3개 출력
print(temp[-3:])
# 처음부터 끝까지 출력(2칸씩 건너뛰어서)
print(temp[::3])
# 전체출력 처음부터 끝까지 스텝은 1개씩 증가 결국 전체출력
print(temp[::1])
# 전체출력 처음부터 끝까지 스텝은 1개씩 꺼꾸로 증가면서 전체출력 --> 뒤집는다
print(temp[::-1])

84
26 26
[84 36 91]
[11 92 26]
[84 70 26 26]
[84 36 91 70 10 42 26 11 92 26]
[26 92 11 26 42 10 70 91 36 84]


In [20]:
# 1부터 100 숫자중에 임의의 숫자 20개를 생성
temp = np.random.randint(1,100,20)
# 짝수들의 합을 구해보세요
print(sum(temp[temp % 2 == 0]))
# 3의 배수들만 출력
print(sum(temp[temp % 3 == 0]))

674
411


In [21]:
temp = np.array([1,2,3])
temp[ [True,True,False  ]  ]

array([1, 2])

2차원 배열 또는 행렬

In [22]:
temp = np.random.randint(1,10,(5,5))
temp[1:4, 1:4]

array([[4, 4, 9],
       [9, 9, 1],
       [8, 5, 6]])

In [23]:
temp[:, 1:4]

array([[9, 6, 2],
       [4, 4, 9],
       [9, 9, 1],
       [8, 5, 6],
       [7, 7, 6]])

In [24]:
temp[1:4,:]

array([[7, 4, 4, 9, 3],
       [7, 9, 9, 1, 8],
       [8, 8, 5, 6, 6]])

In [25]:
temp = np.random.randint(1,10,(2,5))
temp

array([[1, 1, 9, 4, 6],
       [2, 8, 2, 1, 4]])

In [26]:
sum(temp)

array([ 3,  9, 11,  5, 10])

In [27]:
np.sum(temp,axis=0)

array([ 3,  9, 11,  5, 10])

In [28]:
np.sum(temp,axis=1)

array([21, 17])

데이터의 모양 보기
  - shpae

In [29]:
# 1 ~ 100 사이의 숫자중에서 임의수로 (5,6) 행렬/집합/배열 을 만들어보세요

In [30]:
temp = np.random.randint(1,100,(5,6))
temp

array([[54, 80,  4, 69,  4, 76],
       [59, 37, 39, 83, 32,  9],
       [ 6, 22, 63, 69, 67, 87],
       [91, 51, 78, 53,  7, 20],
       [ 4, 30, 64, 86, 11,  3]])

In [31]:
temp.shape

(5, 6)

In [32]:
temp.reshape(6,5)

array([[54, 80,  4, 69,  4],
       [76, 59, 37, 39, 83],
       [32,  9,  6, 22, 63],
       [69, 67, 87, 91, 51],
       [78, 53,  7, 20,  4],
       [30, 64, 86, 11,  3]])

In [33]:
# row:행을 2개로 하면
temp.reshape(2,15)

array([[54, 80,  4, 69,  4, 76, 59, 37, 39, 83, 32,  9,  6, 22, 63],
       [69, 67, 87, 91, 51, 78, 53,  7, 20,  4, 30, 64, 86, 11,  3]])

In [34]:
temp.reshape(2,-1)

array([[54, 80,  4, 69,  4, 76, 59, 37, 39, 83, 32,  9,  6, 22, 63],
       [69, 67, 87, 91, 51, 78, 53,  7, 20,  4, 30, 64, 86, 11,  3]])

In [35]:
temp.reshape(-1,15)

array([[54, 80,  4, 69,  4, 76, 59, 37, 39, 83, 32,  9,  6, 22, 63],
       [69, 67, 87, 91, 51, 78, 53,  7, 20,  4, 30, 64, 86, 11,  3]])

In [37]:
temp.reshape(-1).shape

(30,)

In [45]:
arr = np.array([1,2,3])
arr,  arr.shape

(array([1, 2, 3]), (3,))

In [46]:
# 0번 축에 차원 추가
temp = np.expand_dims(arr, axis=0)
temp, temp.shape

(array([[1, 2, 3]]), (1, 3))

In [49]:
# 0번 축에 차원 추가
temp = np.expand_dims(arr, axis=1)
temp, temp.shape

(array([[1],
        [2],
        [3]]),
 (3, 1))

차원제거

In [52]:
arr = np.array([[[1,2,3]]])
arr, arr.shape

(array([[[1, 2, 3]]]), (1, 1, 3))

In [54]:
np.squeeze(arr)

array([1, 2, 3])

In [58]:
np.squeeze(arr,axis=0)

array([[1, 2, 3]])

In [59]:
np.squeeze(arr,axis=1)

array([[1, 2, 3]])

In [61]:
arr = np.array([ [ [1],[2],[3]  ] ] )
arr, arr.shape

(array([[[1],
         [2],
         [3]]]),
 (1, 3, 1))

In [66]:
np.squeeze(arr,axis =2 )

array([[1, 2, 3]])

- np.squeeze 는 차수를제거하는데.. 차수의 모양이 1이 차수들만 제거한다.
- np.expend_dims 는 반대 개념..

In [68]:
arr.ndim, arr.shape

(3, (1, 3, 1))

- 넘파이 배열 만들기  넘파이 랜덤함수
- 넘파이끼리 연산
- 넘파이와 정수의 연산
- 넘파이 모양보기
- 넘파이 모양 바꾸기
- 넘파이 불필요한 차수 제거하기
- 넘파이 차수 추가하기
- 넘파이 리스트 슬라이싱으로 다양하게 데이터 가져오기

In [70]:
# 넘파이 배열 만들기 넘파이 랜덤함수
temp = np.random.randint(1,100,(10,15))
temp % 2 == 0

array([[ True,  True, False, False,  True, False, False, False, False,
         True, False,  True,  True, False, False],
       [False, False, False,  True, False,  True, False,  True,  True,
         True,  True, False,  True, False, False],
       [ True, False, False, False,  True, False,  True, False, False,
         True, False,  True, False, False, False],
       [False,  True,  True, False, False,  True, False, False,  True,
        False, False,  True,  True, False, False],
       [False,  True, False,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False],
       [False,  True,  True, False, False, False,  True, False, False,
        False,  True, False, False,  True,  True],
       [False, False, False,  True,  True, False,  True, False, False,
         True,  True,  True, False,  True,  True],
       [ True,  True,  True, False,  True, False, False, False, False,
         True,  True, False,  True, False, False],
       [False,  True, Fa

In [71]:
temp[ temp % 2 == 0 ]

array([86, 92,  4, 52, 96, 20, 20, 62, 50, 78, 26, 94, 62,  6, 58, 88, 44,
       94,  6, 74, 30, 22, 10, 72, 42, 62, 56, 42, 40, 38, 56, 32, 88, 22,
        6, 34, 36, 70, 78, 30, 50, 52, 80, 90, 40, 34, 74, 14, 52, 52, 24,
       94, 44, 72, 48, 84, 48, 90, 60, 98, 66, 72, 46, 34, 32, 54, 80, 66])

In [72]:
# 넘파이끼리 연산
temp_1 = np.random.randint(1,10,(2,3))
temp_2 = np.random.randint(1,10,(2,3))
temp_1 * temp_2

array([[12, 63, 36],
       [ 2, 21,  4]])

In [73]:
temp_1 * 10

array([[20, 70, 90],
       [10, 70, 40]])

In [74]:
temp_1.shape

(2, 3)

In [75]:
# 넘파이 모양 바꾸기
temp_1.reshape(3,2)

array([[2, 7],
       [9, 1],
       [7, 4]])

In [81]:
# 넘파이에 데이터 추가
np.append(temp_1,10)
# 넘파이에 데이터 제거
np.delete(temp_1,0)

array([7, 9, 1, 7, 4])

In [82]:
# 넘파이 불필요한 차수 제거하기
# 리스트에 데이터를 추가하는데.. 추가하기위해서 로직을 수행하다보면
# 리스에 추가할 값이 정수 및 데이터라고 생각했는데... ex temp.appned(10)
# 리스에 추가할 값이 정수 및 데이터라고 생각했는데... ex temp.appned([10])

In [90]:
def some_process(data):
  if sum(data) > 20:
    return [data]
  else:
    return data

In [91]:
temp = np.random.randint(1,10,10)
result = []
result.append(some_process(temp))
result

[[array([1, 5, 6, 1, 7, 9, 1, 9, 4, 3])]]

In [93]:
result = np.array(result)
result

array([[[1, 5, 6, 1, 7, 9, 1, 9, 4, 3]]])

In [96]:
np.squeeze(result,axis=0)

array([[1, 5, 6, 1, 7, 9, 1, 9, 4, 3]])

In [97]:
np_1 = np.random.randint(1,10,(2,3))
np_2 = np.random.randint(1,10,(3,2))
np_1 + np_2  # reshape로 변경

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [99]:
np_1@np_2  # 내적연산

array([[64, 94],
       [64, 82]])

In [105]:
# (2,1)
np_1 = np.random.randint(1,10,(2,1))
np_1

array([[6],
       [6]])

In [106]:
np_1 + 2  # shape 가 안맞아도.. 내부에서 브로드캐스팅이 되어서 연산이 가능

array([[8],
       [8]])

In [107]:
np_2 = np.array([2])
np_2

array([2])

In [108]:
np_1 + np_2

array([[8],
       [8]])

In [110]:
np_1.shape ,  np_2.shape

((2, 1), (1,))

In [111]:
np.expand_dims(np_2,axis=0)

array([[2]])

In [112]:
np.expand_dims(np_2,axis=0) + np_1

array([[8],
       [8]])

In [ ]:
# 차원을 제거하거나 추가해야 하는경우
# 이미지를 다룰때.. (채널, 가로 ,세로)
# 흑백이미지를 데이터 사용할 ()